http://localhost:8080
-k
Content-Type: application/json; charset=utf-8
--
--
GET /api/device/32bebf5d-2773-4725-8e26-6c9aa2f7e2ae

--
POST /api/device
{
    "name": "my device 2",
    "kind": 99,
    "location": "3400078d-9f5f-4ab2-924d-4d5124ed1d6b",
    "desc": "another important gadget"
}

--
GET /api/location/3400078d-9f5f-4ab2-924d-4d5124ed1d6b
--
GET /api/location/3400078d-9f5f-4ab2-924d-4d5124ed1d6b/devices

--
POST /api/location
{
    "name": "naviland",
    "latitude": 0.1,
    "longitude": 0.2
}

--
POST /api/observation
{
    "name": "water_level",
    "value": 0.1,
    "deviceId": "3400078d-9f5f-4ab2-924d-4d5124ed1d6b"
}

